name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  all:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun test
      - run: bun run format
      - run: bun x playwright install --with-deps
      - run: bun run test:integration
      - run: bun run build